### ISSUE TITLE
perlre "/x and /xx" Details link doesn't work

### ISSUE THREAD

**Issue by jay** [OpusVL/perldoc.perl.org#100]
Go to perl regex page for modifiers, section [x and xx](https://perldoc.perl.org/perlre.html#*x*-and-*xx*). It says "Details in [/x and /xx](https://perldoc.perl.org/perlre.html#%2fx-and-%2fxx)" but that link doesn't go anywhere.

(_May be related to #35? I'm not sure._)

**Comment by Grinnz** [comment]
This is not related to #35, it's because there are no anchors generated for list items.

**Comment by jay** [comment]
Fixed
