### ISSUE TITLE
String multiplication at Perl intro page ambiguous.

### ISSUE THREAD

**Issue by Permik** [OpusVL/perldoc.perl.org#105]
Hi!

There's a mention of the string multiplication at
[the miscellaneous section](https://perldoc.perl.org/perlintro.html#Miscellaneous) of the Perl intro page.  
I think the description could be made more clear by adding "repeats strings" in to parenthesis after the description like in the range operator.

It's really ambiguous right now, and requires further reading if you want to know what it does.

**Comment by karenetheridge** [comment]
The content is managed at https://github.com/Perl/perl5. Perhaps you would like to send a pull request?

**Comment by Permik** [comment]
Oh, didn't catch that!  
I'll do it right away!

Sorry for the unnecessary spam.
