### ISSUE TITLE
https://perldoc.perl.org/perl5203delta.html says "Perl 5 version 30.0"

### ISSUE THREAD

**Issue by sjvudp** [OpusVL/perldoc.perl.org#108]
I was expecting perl5203delta to contain info about Perl 5.20.3, but the title says "Perl 5 version 30.0".
Similar for https://perldoc.perl.org/perl5220delta.html

**Comment by Grinnz** [comment]
That's because it's the perldelta for 5.20.3 included with 5.30.0 (all prior perldeltas are included in successive releases of Perl). You have to use the version dropdown to go to the documentation as it was included in different releases.

**Comment by Grinnz** [comment]
The Perl version being a page heading is pretty misleading, https://github.com/OpusVL/perldoc.perl.org/issues/65 is relevant

**Comment by sjvudp** [comment]
I still don't quite get it: The summary page says "perl5200delta - what is new for perl v5.20.0 ", but when I open it, I see "
Perl 5 version 30.0 documentation
perl5200delta". Do you mean "This file documents the changes in Perl 5.20.0 for the Perl release 5.30"?

**Comment by Grinnz** [comment]
It is part of the 5.30.0 documentation, showing historically what was new in 5.20.0.

**Comment by sjvudp** [comment]
OK, OK. Congrats: You confused the Russians ;-)
