### ISSUE TITLE
Link in gmtime doc to localtime is actually to gmtime

### ISSUE THREAD

**Issue by jay** [OpusVL/perldoc.perl.org#118]
Go to [gmtime doc](https://perldoc.perl.org/functions/gmtime.html#localtime-EXPR). It says "Works just like [localtime](https://perldoc.perl.org/functions/gmtime.html#localtime-EXPR)" but that link is to gmtime not localtime.

Also the search box doesn't work from that page. For example go to the top and type gmtime or localtime and search and it will say no results.

**Comment by Grinnz** [comment]
Duplicate of #35 and #74

**Comment by jay** [comment]
Right you are. I didn't figure this issue was widespread. Sorry for the noise.
