### ISSUE TITLE
FAQ main page ToC links do nothing

### ISSUE THREAD

**Issue by openstrike** [OpusVL/perldoc.perl.org#135]
The table of contents at the very top of https://perldoc.perl.org/perlfaq.html contain links within the page for easy navigation. However, the subset of those links within the "THE QUESTIONS" sub-list apparently do nothing.

eg. The link to section 9 has target https://perldoc.perl.org/perlfaq.html#the-perlfaq9-manpage%3a-Web%2c-Email-and-Networking but that anchor farther down the page is actually ```<a class='view-head2' id="the-perlfaq9-manpage%3a-Web%2c-Email-and-Networking">``` and it appears that the URL encoding in the ```id``` attribute there is to blame.

**Comment by openstrike** [comment]
The URL encoding of the id attributes appears to have been fixed. Thanks.

**Comment by karenetheridge** [comment]
Note that perldoc.perl.org no longer points to the code represented by this repository. It is now served by https://github.com/Grinnz/perldoc-browser.
