### ISSUE TITLE
Mistake in perrecharclass

### ISSUE THREAD

**Issue by kernschmelze** [OpusVL/perldoc.perl.org#136]
In the section "Special Characters Inside a Bracketed Character Class"
there is this: 

  $a =~ m/[$,]/;        # double-quotish: matches "\t", "|", or " "

That looks utterly wrong to me.

**Comment by Grinnz** [comment]
This is the issue tracker for the perldoc.perl.org web site. The perl documentation issue tracker is here: https://github.com/Perl/perl5/issues

**Comment by kernschmelze** [comment]
Ok.
Reported there:
https://github.com/Perl/perl5/issues/17892
