### ISSUE TITLE
List formatted without bullets

### ISSUE THREAD

**Issue by autarch** [OpusVL/perldoc.perl.org#15]
The list of items from Damian at https://perldoc.perl.org/5.30.0/perlootut.html#When-to-Use-OO is formatted as a list in the pod. The CSS for the page is formatting this without any bullets, which looks weird.

I'd assume this issue affects other pages but I just happened to notice it here.

**Comment by pablrod** [comment]
Some lists also have a **30** instead of the bullet, for example at https://perldoc.perl.org/perlre.html#Modifiers that has the perldoc:
```
=over 4

=item m
X</m> X<regex, multiline> X<regexp, multiline> X<regular expression, multiline>
```

**Comment by eulmatxlm** [comment]
Quick note, the **30** is the current perl version. See:
https://perldoc.perl.org/5.28.2/perlre.html

**Comment by cxw42** [comment]
Repro for the `30` in [perlvar](https://perldoc.perl.org/perlvar.html#%24%22) - I found it confusing when I first saw it.  Thanks for looking into this!

**Comment by JohnMica** [comment]
this has been fixed in the new beta release
