### ISSUE TITLE
Migrate the perldoc.perl.org domain to perldoc.pl

### ISSUE THREAD

**Issue by briandfoy** [OpusVL/perldoc.perl.org#153]
As much as I'd like to fix all the problems this site has, it's a waste of time when we already have a working alternative that's actively maintained. I hate to see the site so broken when I link to it so often in my books, Stackoverflow answers, and anywhere else I write. It's not a good situation for the current sponsor or the community. 

Let's migrate this to Grinnz's perldoc.pl. I've tested all the perldoc links in Learning Perl and his site handles them all just fine.

**Comment by scottchiefbaker** [comment]
I second this... There are far too many bugs on the "official" site that aren't being addressed in a timely fashion.

**Comment by Grinnz** [comment]
FWIW, previous discussion: https://github.com/OpusVL/perldoc.perl.org/issues/45

The site is compatible with almost all perldoc URLs currently in use with the exception of some customized index pages which I plan to add redirects or replacements for as appropriate: https://github.com/Grinnz/perldoc-browser/issues/17

There are other improvements planned which I would be happy to prioritize if this was to be the plan, and of course it already has a search that works far better than even the old site's search, if I say so myself. I am also open to theming adjustments particularly in color scheme and branding.

**Comment by PaulGWebster** [comment]
Indeed the site search is something that does need some significant improvement on the old site

**Comment by briandfoy** [comment]
I've been told that OpusVL is willing to relinquish the domain but that the TPF board needs to vote on what happens next. That vote should happen this week. The board members are listed on the [TPFs Who's Who](https://www.perlfoundation.org/whos-who.html) page.

**Comment by rspier** [comment]
Huh? TPF doesn't control the DNS for this.

**Comment by briandfoy** [comment]
> Huh? TPF doesn't control the DNS for this.

So, who does control the DNS? I'm just reporting what TPF told me.

**Comment by rspier** [comment]
noc.perl.org

Start an email thread with me, @Grinnz , and @JohnMica or someone else from OpusVL.

**Comment by briandfoy** [comment]
@rspier Taking that offline with you, but yes, there's already an email thread out there.

**Comment by oalders** [comment]
@briandfoy could you loop me in on this email conversation?

**Comment by briandfoy** [comment]
> @briandfoy could you loop me in on this email conversation?

Done. And @rspier isn't on the email alias I thought he was, which is why he was confused (rather, I confused him). Also, Robert set me straight on TPFs role here, but I'll let him explain that offline if needed.

**Comment by briandfoy** [comment]
It seems that everyone has come to an agreement and the domain will be migrated soon.

**Comment by matthewpersico** [comment]
It appears to have been done:

http://perldoc.perl.org/
