### ISSUE TITLE
Cannot scroll with arrow keys unless I first click on the page body

### ISSUE THREAD

**Issue by autarch** [OpusVL/perldoc.perl.org#16]
When I first load any page, hitting the down arrow doesn't cause the page to scroll. If I click somewhere below the header than it starts working.

Using my scroll wheel does work without clicking.

I'm assuming this has to do with the fixed nav header.

**Comment by hakonhagland** [comment]
I cannot scroll with arrow keys or the mouse wheel even if I click the page first. I am using Google Chrome. Dragging the scrollbar at the right edge works, but the scroll bar is hidden by the header so it is not easy to realize there is a scroll bar there.

**Comment by eulmatxlm** [comment]
Same issue with firefox. Edge works though.
Incidentally, the bar goes under the nav header **and** the "this is a beta release" link.

**Comment by JohnMica** [comment]
i can confirm this is a strange issue indeed.

will investigate and hopefully fix is

**Comment by hakonhagland** [comment]
RE: *"I cannot scroll with arrow keys or the mouse wheel ..."* I think the problem is related to the [SmoothScroll](https://github.com/gblazex/smoothscroll) chrome extension. If I disable this extension, the page scrolling starts to work again..

**Comment by JohnMica** [comment]
fixed in next release
- updating libs to latest versions

**Comment by autarch** [comment]
I'm still having this issue.
