### ISSUE TITLE
Fixed navbar header makes navigation to fragments wonky

### ISSUE THREAD

**Issue by autarch** [OpusVL/perldoc.perl.org#17]
When I go to https://perldoc.perl.org/5.30.0/perldelta.html#Deprecations from the TOC I'd expect to see the "Deprecations" header. Instead, the header is hidden by the fixed navbar, as is that header's sub-header.

**Comment by cxw42** [comment]
Repro on Chrome 74.0.3729.169 (Official Build) (64-bit) (cohort: Stable).  (Admittedly, as I recall the old site had the same problem ;) ).

(Thanks for putting together the new site!  I especially like the version dropdown.)

**Comment by JohnMica** [comment]
thanks for the issue reporting.

i guess since the navbar is fixed a solution would be to add a padding / offset so that scrolling will show the title just under the navbar. 
will be fixed in the next iteration (soon)

**Comment by ailin-nemui** [comment]
I played a lot with this issue on another site, and ultimately (personal opinion) found it better to avoid the fixed header altogether. This has the added benefit of giving more valuable screen space to the content especially on mobile.

**Comment by Grinnz** [comment]
I reached that same conclusion on perldoc.pl, particularly because both possible solutions I could find are messy - one requiring CSS which can make the page not work as expected, and one requiring JS which won't work for someone who has JS disabled.

**Comment by JohnMica** [comment]
this has been released into the new beta release

**Comment by cxw42** [comment]
@JohnMica I am still seeing the old behaviour at https://perldoc.perl.org/5.30.0/perldelta.html#Deprecations - is the new beta release at a different URL?
