### ISSUE TITLE
Search text input

### ISSUE THREAD

**Issue by hurricup** [OpusVL/perldoc.perl.org#18]
Actively using perldoc and this is very important control in my opinion. Where is it now?

**Comment by JohnMica** [comment]
it is coming up shortly

since this is a beta release, we are trying to fix potential issues that we missed in dev.

for sure the next iteration will have a search functionality as well as other fixes

**Comment by shadowcat-mst** [comment]
Search already works perfectly on http://perldoc.pl/ - which is a community replacement for the engine of perldoc.perl.org - hence why e.g. http://p3rl.org/ now redirects to perldoc.pl just like it switched to redirecting to metacpan instead of search.cpan.org.

**Comment by JohnMica** [comment]
search has been released in the new beta release.

not perfect yet  - but i would suggest that any missing terms to be reported as a new issue to simplify the investigation into them
