### ISSUE TITLE
Broken links in the footer

### ISSUE THREAD

**Issue by eulmatxlm** [OpusVL/perldoc.perl.org#19]
Hello,
just a quick note, the links in the footer are almost all broken, whereas they work in the quick menu from the nav bar.

For example, "perlop" from the menu bar:
- https://perldoc.perl.org/5.30.0/perlop.html

From the bottom bar, the 'dot' in the version are replaced with '/':
- https://perldoc.perl.org/5/30/0/perlop.html

**Comment by eulmatxlm** [comment]
Funnily enough, on the resulting 404 page, the bottom links are correct...

**Comment by JohnMica** [comment]
thanks for the issue reporting.
this has been fixed and will be deployed soon to the live site as well.
