### ISSUE TITLE
Navbar hides scroll bar

### ISSUE THREAD

**Issue by stefanos82** [OpusVL/perldoc.perl.org#20]
Before start scrolling:

![image](https://user-images.githubusercontent.com/1777466/59204795-0d93c500-8baa-11e9-8094-dcb27ed4ff30.png)

After reaching "using character classes" becomes visible:

![image](https://user-images.githubusercontent.com/1777466/59204836-29976680-8baa-11e9-9fb4-8c7ffaf59a4f.png)

**Comment by Grinnz** [comment]
Bootstrap [fixed placement](https://getbootstrap.com/docs/4.3/components/navbar/#placement) would be a better choice for this, though it does not fix the annoying anchor position problem (#17)

**Comment by JohnMica** [comment]
@Grinnz indeed we've considered the position sticky but implementation by browser vendors is not that great https://caniuse.com/#feat=css-sticky

also webkit (safari and iOS) has a magical repainting effect while scrolling with a position fixed - which i believe has been resolved in the next iteration

**Comment by JohnMica** [comment]
fixed in next release
