### ISSUE TITLE
Header dropdown vs footer links

### ISSUE THREAD

**Issue by matthewpersico** [OpusVL/perldoc.perl.org#21]
You have some name inconsistencies:
Manuals|Footer|
-|-
Overview|
Tutorials|
FAQs|
History/Changes|Changes
Licence|
Language|
Functions|
Operators|
Special Variables|Variables
Pragmas|
Utilities|
Internals|
Platform Specific|Platforms

**Comment by JohnMica** [comment]
I see what you mean.

since there is more space in the header the naming is a bit more descriptive. mostly the same but with the differences you specified.

the next iteration will have the Naming identical so that it won't cause confusion.

**Comment by JohnMica** [comment]
fixed in next release
 - uniform naming scheme
