### ISSUE TITLE
Link to this bugtracker in the "about" info

### ISSUE THREAD

**Issue by avar** [OpusVL/perldoc.perl.org#23]
It just says "docs maintained by p5p", should also link to the maintainers of the site itself (just notes that OpusVL hosts it).

**Comment by JohnMica** [comment]
where is this this 'docs maintained by p5p' ? 

OpusVL is not hosting the website, only the development side of things.

**Comment by tm604** [comment]
> where is this this 'docs maintained by p5p' ?

Front page:

![image](https://user-images.githubusercontent.com/2883904/59758031-97851180-92bf-11e9-9df1-d315ec4c96c7.png)

and the link goes to https://lists.perl.org/list/perl5-porters.html if that makes it easier to find?

**Comment by JohnMica** [comment]
got it, thanks

**Comment by JohnMica** [comment]
clarified the text in the footer.
