### ISSUE TITLE
On MacOS/Safari 12.1 (13607.1.40.1.5), page decorations obscure the scrollbar

### ISSUE THREAD

**Issue by sbs60** [OpusVL/perldoc.perl.org#24]
Using Safari 12.1 on MacOS 13, visit a perldoc site, e.g., https://perldoc.perl.org/perlrecharclass.html
The top banner extends across the entire window including the scroll bar.  The scroll bar is still usable, but unresponsive in the obscured region: you have to click in an unobscured region and then drag back to where you want to be.  To keep control of the scrollbar while reading in a page region whose scroll position is obscured, keep holding down the mouse button/trackpad.

Perhaps ironically, the little banner that helpfully advises me to report issues on github also obscures the scrollbar.  That banner's contents could more modestly be put in the top banner, along with a "Visit production version of this beta site" link.

MacOS preferences (Preferences/General panel) provide user control over the scrollbar appearance, including whether/when it appears at all.  I use Always in the Show scrollbars item, and did not examine perldoc's behavior in the other cases.

**Comment by JohnMica** [comment]
this has to do with webkit implementations for the window scrollbars.

a fix is in the works and hopefully will be released with the next iteration

**Comment by JohnMica** [comment]
fixed in next release
