### ISSUE TITLE
Perl Web Manual non-functional

### ISSUE THREAD

**Issue by RonBOakes** [OpusVL/perldoc.perl.org#25]
The Beta 5.30 version of the web Perl manual is nearly non-functional:
- Search does not work, and is not available from most command pages
- Links from at least some pages - for example readdir from opendir - are missing.

While this is listed as a Beta version, this is a huge step back in the functionality of the Perl online documentation that I use regularly when I am programming in Perl - a resource I rely on since my paper Perl reference material is at home and my primary development system is air-gapped limiting my ability to use perldoc at the command line.

**Comment by airencracken** [comment]
It's pretty unusable.

**Comment by JohnMica** [comment]
- search has been added to the next release

- some bugs are still present (therefor a beta release) but we aim to fix these issues in an iterative way.

**Comment by JohnMica** [comment]
search has been implemented in the current beta.

for any missing terms with the search, please open a new issue
