### ISSUE TITLE
PERLDOC Interface unusable...

### ISSUE THREAD

**Issue by stdioLib** [OpusVL/perldoc.perl.org#27]
A better advertisement for Python would be difficult to imagine...

Search is unspeakable. The bullets on the technical pages aren't bullets; they are the number "30"(?). The links at the bottom of the main page are not useful to the technical community; mostly it looks like advertising. The links behind the letters in the functions page don't take the top banner into account and put the reader 3 lines below where he/she asked to be. The drop downs are fine for the versions but the links to functions, tutorials, etc. should be visible at all times.

Please read Edward Tufte's books about data density and information displays. The empty, "clean" look is vacuous. If you don't make organizing and communicating information the most important design criteria of the site, it really won't matter how easy it is to read. Find a way to put every bit of information you can think of in plain sight... If you need an example, look at the pre-beta version!

I use PERLDOC to reference technical information all the time and this looks like marketing got hold of it and shook all the information out of it... and I'm sorry to rant but this is a big loss from my professional toolbox.

**Comment by shadowcat-mst** [comment]
Most of the IRC community at least now uses http://perldoc.pl/ - you might find that more to your taste

**Comment by ANSI-C** [comment]
> Most of the IRC community at least now uses http://perldoc.pl/ - you might find that more to your taste

many many many thanks for the tip!

**Comment by nuclight** [comment]
I vote for returning the old rendering at least for desktops.

**Comment by JohnMica** [comment]
new beta release has
- search implemented
- numbers instead of bullets has been fixed

thanks for the advice on the book
