### ISSUE TITLE
perl version sorting is inconsistent in pulldown

### ISSUE THREAD

**Issue by rspier** [OpusVL/perldoc.perl.org#3]
It's 

28
  5.28.0
  5.28.1

26
  5.26.0
  5.26.1
  ...

I'd expect:

5.28
  5.28.1
  5.28.0

5.26
  5.26.3
  5.26.2
  ...

I.e. purely reverse chronological

**Comment by JohnMica** [comment]
i believe on the testing site this has been achieved
