### ISSUE TITLE
Wrapping in footer links is nonsensical.

### ISSUE THREAD

**Issue by FGasper** [OpusVL/perldoc.perl.org#30]
![image](https://user-images.githubusercontent.com/844867/59226032-29926900-8ba0-11e9-906c-f681539fbe10.png)
Please don’t make this yet another page that assumes everyone’s viewport is either mobile or super-wide. :)

**Comment by JohnMica** [comment]
seems only webkit browsers did the magical word-break for the text.

has been removed for the next iteration

**Comment by JohnMica** [comment]
fixed in next release
