### ISSUE TITLE
Bring back the left nav menu

### ISSUE THREAD

**Issue by haukex** [OpusVL/perldoc.perl.org#32]
First of all, thank you very much for putting work into upgrading perldoc.perl.org!

IMHO it's too bad the left nav menu is gone, I used this all the time - now one click is two, I need to drop down the top right menu and then pick the item I want. It would be great if there was a side nav menu like on the old version.

**Comment by cherio** [comment]
This is indeed a great usability regression. What used to take one click and two seconds now takes noticeably longer to navigate in the hierarchy of links.

**Comment by JohnMica** [comment]
for now there will be no left nav menu being implemented. 

i cannot speak fo the future though.

**Comment by haukex** [comment]
Thanks for the reply, I'm a bit confused though.

May I ask how this design decision was made, taking into consideration what I mentioned about links now being hidden behind another click? Personally I feel that it strongly affects the usability of the site, but that's just me - perhaps you got overwhelming feedback or other data as to the menu not being necessary?

And if this might get addressed in the future, why not leave the issue open until then?
