### ISSUE TITLE
perldoc html zip for offline review

### ISSUE THREAD

**Issue by raginijx** [OpusVL/perldoc.perl.org#33]
Hello,

The new website is impressive.  How does one download the perldoc html zip file for offline review ?

**Comment by JohnMica** [comment]
thanks @raginijx .

there is no PDF / zip  to download at this time.
It could be something on the roadmap

**Comment by PaulGWebster** [comment]
It is possible to get the 'static;' site in its entirety by cloning or downloading as zip from this repository: https://github.com/OpusVL/perldoc.perl.org-export
