### ISSUE TITLE
Readability improvement concerning maximum page width

### ISSUE THREAD

**Issue by smonff** [OpusVL/perldoc.perl.org#37]
When using the page full screen on a reasonably large screen, the paragraphs of text or code   are way too large: this is because the `article.col-sm-12` container have a `max-width` of `100%`. Something like `max-width: 65%` would deliver a much easier reading experience (even smaller would be acceptable IMHO).

The eyes are not designed to switch between so long lines: the current layout works well on mobiles or resized windows, and congratulations to you for the improvement comparing to the previous website. But not applying a `max-width` is painful, because it will require people with large windows to constantly resize their browsers.

Consider using a limited `max-width`, maybe not hard coded the way I described and more the *flex* way: it will really improve the readability, like in a text book. A proposal:

![image](https://user-images.githubusercontent.com/1219097/59514776-de3ccb00-8ebd-11e9-89d7-b12539f518ce.png)

For reference see how some other documentations are made: 

![image](https://user-images.githubusercontent.com/1219097/59514832-fdd3f380-8ebd-11e9-86ba-4de5172a23ce.png) (Python)

![image](https://user-images.githubusercontent.com/1219097/59515044-8b174800-8ebe-11e9-9714-61069794f4c0.png) (Ruby)

![image](https://user-images.githubusercontent.com/1219097/59515255-01b44580-8ebf-11e9-84bc-0edeb7c8389e.png) (Go)

I like the Go way: only `<p>` and `<li>` tags are limited to `max-width: 50rem`. I is a nice compromise as it leaves some elements filling the rest of the screen nicely

**Comment by JohnMica** [comment]
i can confirm that when using a wide screen the paragraph widths does indeed becomes longer that what could be found as useful.

there will be a fix in the next iteration

**Comment by smonff** [comment]
Note that the full-width thing can eventually be a popular thing for some people: I just found out that on [perldoc.pl](https://perldoc.pl/), they have an *« Expand »* button on the navigation bar to switch to a full width mode.

🤔

**Comment by Grinnz** [comment]
Yes, this was implemented as a compromise as I see the value of both designs and there are those with both preferences. (see https://github.com/Grinnz/perldoc-browser/issues/6)

**Comment by JohnMica** [comment]
It might become popular however ...

... the longer the string of text, the harder to follow (too much research about this available)

The idea would be to make it easy to follow, read, understand and implement.

**Comment by JohnMica** [comment]
i believe this has been fixed with the new beta release
