### ISSUE TITLE
Please provide backwards-compatibility for search URL

### ISSUE THREAD

**Issue by smammy** [OpusVL/perldoc.perl.org#39]
As the good book says, [Cool URLs don't change](https://www.w3.org/Provider/Style/URI). Please provide backwards-compatibility URL for `https://perldoc.perl.org/search.html`. My Firefox keyword search bookmark is broken. 🙂

**Comment by GPHemsley** [comment]
Indeed, I can't even find a search interface at all in the new documentation.

**Comment by GPHemsley** [comment]
OpusVL/perldoc.perl.org-engine#2 mentions that [perldoc.pl](https://perldoc.pl/) exists (first I've heard of it) that has a search interface that seems to work the same:

`https://perldoc.pl/search?q=%s`

**Comment by JohnMica** [comment]
while search is not present at the moment, it is planned with the next iteration

we understand that search is important, and as this is in a beta stage at present, we are working towards solving most of the issues.

**Comment by GPHemsley** [comment]
@JohnMica If this version of the documentation is still in beta stage, why did you push it to production?

**Comment by LadyAleena** [comment]
The lack of search is bugging me to bits. Why wasn't it part of the redesign from the beginning?

**Comment by JohnMica** [comment]
- search has been added to the next release

**Comment by JohnMica** [comment]
while search is now implemented in the beta release, i do not believe there will be a `search.thml` page anymore.

**Comment by smammy** [comment]
@JohnMica Please reconsider providing a `search.html` for backwards-compatibility. There are existing links out there on the web and you are breaking them by removing that page. Thanks!

**Comment by CollectorOfBolts** [comment]
While we wait (possibly in vane) for search.html to be restored, I have created a user script that at least allows users to set up Perldoc as a search engine in the browser: [https://github.com/CollectorOfBolts/perldoc_search_url_user_script](url)

**Comment by Grinnz** [comment]
You can also use https://perldoc.pl as previously mentioned, which has a proper search that is also set up with opensearch metadata.
