### ISSUE TITLE
Tutorials and utilities on homepage still have lorem ipsum content

### ISSUE THREAD

**Issue by rspier** [OpusVL/perldoc.perl.org#4]
Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.

**Comment by JohnMica** [comment]
fixed in final release
