### ISSUE TITLE
Footer links /5.30.0/ vs /5/30/0/

### ISSUE THREAD

**Issue by douglasdd** [OpusVL/perldoc.perl.org#40]
From https://perldoc.perl.org/5.30.0/index-overview.html the main body links are path-relative (`file`), so they correctly point to, f/ex:

    /5.30.0/index-overview.html

But links in the footer are path-absolute(`/root/path/file`), and are to the wrong base directory (`/` not `.`), f/ex:

    /5/30/0/index-overview.html

If they need to be path-absolute, they should be to 

    /5.30.0/index-overview.html

All the footer links are affected:
  * Manual
      * Overview
      * Tutorials
      * FAQs
      * Changes
  * Reference
      * Lanuage
      * Functions
      * Operators
      * Variables
  * Modules
      * Modules
      * Pragmas
      * Utilities
  * Misc
      * License
      * Internals
      * Platforms

**Comment by JohnMica** [comment]
thanks @douglasdd  for this one.

i believe it has been sorted and it is ready for the next iteration.

**Comment by JohnMica** [comment]
fixed in next release
