### ISSUE TITLE
exploreperl.js javascript file no longer served on new site

### ISSUE THREAD

**Issue by cbrandtbuffalo** [OpusVL/perldoc.perl.org#43]
The Perl Foundation site at https://news.perlfoundation.org has a reference to a script a:
“http://perldoc.perl.org/static/exploreperl.js” and it seems since the update the header for the news site is having issues. It's not specifically related to perldoc, but was this file moved to a new location we might point to?

**Comment by Grinnz** [comment]
It probably would be best to avoid relying on an external site that isn't a CDN for javascript in the future...

**Comment by JohnMica** [comment]
I agree with @Grinnz about the external libraries. 
my guess would be that the library would be moved to the perlfoundation site thus eliminating these potential issues in the future,

also it seems that the site in question will need some updates as well and I am sure that these updates are in the pipeline

**Comment by cbrandtbuffalo** [comment]
Agreed, in the past some resources were shared amongst the perl-related sites, but it does create an invisible dependency. Right now I'm trying to figure out how to get the news.perlfoundation.org site to display correctly again.

**Comment by cbrandtbuffalo** [comment]
We figured out a way to get the old JS code, so this can be closed.
