### ISSUE TITLE
Minimize the height of navbar to allow more reading area space

### ISSUE THREAD

**Issue by smonff** [OpusVL/perldoc.perl.org#44]
On the desktop view, with a relatively small height screen (approx. `1080px`, laptops, etc.), the top navbar  height could be shrunk: it has no reason to occupy so much space when it can easily be *clicked* (I mean not *touched*) and that the user is mostly seeking for reading documentation. 

A high height will create more scrolling interactivity and will remove precious reading area in the case you are seriously reading the documentation and/or trying to understand concepts, what involve to read a bit, coming back to some previous code, etc.

![image](https://user-images.githubusercontent.com/1219097/59751871-946b3080-9281-11e9-938d-1993bd234b20.png)

**Comment by smonff** [comment]
It can be related to #17 (that mention directly this issue in a comment), #32 and #37, but I create a separate issue because the purpose is different.

**Comment by smonff** [comment]
A radical solution is: shrink the oignon image, inline `Perl` and `::DOC` and the height can be greatly optimized:

![proposal](https://user-images.githubusercontent.com/1219097/59753269-10667800-9284-11e9-8af5-1171e4197334.png)

My proposal is maybe going a bit too far and I don't want to interfere with your decisions on the logo,  that looks very good by the way, but I feel like this navbar really looks huge.

**Comment by JohnMica** [comment]
@smonff  thanks for the suggestion, I'll pass this on

**Comment by JohnMica** [comment]
there have been improvements to the height of the navbar

- next release would reflect those changes

- also see #46
