### ISSUE TITLE
Please can we forward perldoc.perl.org to the already stable replacement perldoc.pl ?

### ISSUE THREAD

**Issue by shadowcat-mst** [OpusVL/perldoc.perl.org#45]
Since perldoc.perl.org development basically stopped the community got together and figured out what we wanted from a replacement - and built perldoc.pl, complete with link compatibility to make switching over smooth.

I've been trying to get in touch for over a year to arrange this now - there simply doesn't seem any point to trying to migrate to a half-a-rewrite like this repo when we already have a complete superior rewrite that's proven in production and addresses many issues that have been brought up by users.

The original perldoc.perl.org was a fantastic contribution, and I'd hope that it's understood that the building of a version 2 and my choice to be involved in the feature/spec process for that should be taken as a massive compliment in terms of the original'is utility, but at this stage I genuinely believe it's time to move on (and avoid duplicating work already done and deployed).

**Comment by Grinnz** [comment]
For what it's worth, I have opened issues for perldoc.pl based on the items mentioned by @NetworkNode that I can act on. Please feel free to add feedback to any issues labeled "question" or open new issues for other concerns. Casual users are a primary target audience but feedback from them is rare so far.

**Comment by JohnMica** [comment]
this does not seem to be the right place to discuss issues about a different project.

feel free to reference such issues between projects but discuss the issues where they belong.

**Comment by Grinnz** [comment]
Apologies for the sidetrack, but that was not the purpose of this ticket.

**Comment by nuclight** [comment]
https://perldoc.pl is banned in some countries, at least Russia (governments are blocking entire segments in war with e.g. Telegram, many innocent sites are also affected). And if one need web-docs (instead of usual local `perldoc`), then most likely tools to circumvent censorship (VPN, etc.) are not available at that place. So just forwarding is not an option.

**Comment by Grinnz** [comment]
@nuclight I have not forgotten that issue (https://github.com/Grinnz/perldoc-browser/issues/7). CNAME is not a redirect. If it's IP based, additional servers can easily be deployed to mitigate the issue should this path be chosen.
