### ISSUE TITLE
Navbar is too hight

### ISSUE THREAD

**Issue by Ilya33** [OpusVL/perldoc.perl.org#46]
Hello.

Navbar height is 96px. It takes up too much space on laptops with aspect ratio 16:9.

Best Regards, Ilya Pavlov

**Comment by smonff** [comment]
> the design is trying to complement the perl.org website

On perl.org, the top bar is not fixed, so it don't stay in the way when scrolling in the page.

**Comment by JohnMica** [comment]
search and ease to get to all the potential modules / functions / etc .... were factors in deciding to have the navbar always present
