### ISSUE TITLE
"This is a beta release" tag is confusing. 

### ISSUE THREAD

**Issue by adinaa** [OpusVL/perldoc.perl.org#47]
When I see "This is a beta release", it implies that the version of Perl that I'm looking at is in beta. I'm pretty sure that's not the case because I see that tag for all versions of Perl. But it's  confusing. 

If you're trying to say that the website is in beta, I believe the usual convention is to also provide a link to a non-beta version. Is there such a thing? 

Please change the label to say "This website is a beta release...".

**Comment by JohnMica** [comment]
updated this to clarify this confusion

- next release should fix this

**Comment by JohnMica** [comment]
i believe this has been fixed on the current beta release

**Comment by adinaa** [comment]
The tag is still there on the website.

**Comment by JohnMica** [comment]
@adina

The tag is still present as it is still a beta release and some functionality might not work as expected. (The search for instance)

Regards,

John Mica
