### ISSUE TITLE
The navbar overlaps the my browser's scrollbar

### ISSUE THREAD

**Issue by eldering** [OpusVL/perldoc.perl.org#48]
The top navigation/menu bar (besides taking up way to much space) overlaps the scrollbar. This makes it difficult to see where on the page I am and to instantly move back to the top of the page by clicking the scrollbar.
This is on Firefox 60 ESR on Debian Linux.

**Comment by saberworks** [comment]
Also does it on latest version of firefox.  The "beta" banner in the bottom left also covers the scroll bar.  It seems whack that browsers even allow this, but in any case it should be fixed.

**Comment by JohnMica** [comment]
see #20 

- it's already been fixed for the next release
