### ISSUE TITLE
Page decorations still obscure the scrollbar

### ISSUE THREAD

**Issue by aka-sps** [OpusVL/perldoc.perl.org#49]
As in #24, #20 and #48 "This is a beta version" hides part of the scroll bar.
Mozilla Firefox (Win10-64) (if you're interested).

Please **do not use space outside the page**. Nowhere. Never.
Do not provoke erroneous clicks.
This is technical documentation, not a website with intrusive advertising.

@JohnMica
Last but not least. Do not close the issue (i.e. #20, #24, #48 ) until you receive confirmation from the bug reporter.
It is not reason to close public issue:
> it's already been fixed for the next release

or
> fixed in next release

If there are no **public** changes, there is no **confirmation** from the reporter - you should not close the issue.

Thank you for understanding

**Comment by JohnMica** [comment]
this has been fixed in the new beta release
