### ISSUE TITLE
use of camel requires notice

### ISSUE THREAD

**Issue by rspier** [OpusVL/perldoc.perl.org#5]
perl.org has:
The use of the camel image in association with the Perl language is a trademark of O'Reilly Media, Inc. Used with permission.
on https://www.perl.org/siteinfo.html

The link to O'Reilly's page on the subject redirects somewhere generic.  Wayback machine has: https://web.archive.org/web/20180425080044/http://archive.oreilly.com:80/pub/a/oreilly/perl/usage

**Comment by JohnMica** [comment]
Asked for permission to use the camel image. 

Now it is time to just wait and see

**Comment by JohnMica** [comment]
seems that O'Reilly doesnt want to grant us permission to use the camel on the new redesigned website.

this means either:

1 - you guys can get permission

2 - we need a new image 

please le me know what your suggestion might be

**Comment by JohnMica** [comment]
no permission so removed the camel image completely.
because the onion doesnt look good on the page, i have not included it as an image for the hero
