### ISSUE TITLE
strange number rendered over =item

### ISSUE THREAD

**Issue by stphnlyd** [OpusVL/perldoc.perl.org#50]
Now on each =item there is a "30". What's that for?

For example
https://perldoc.perl.org/perlvar.html#General-Variables
https://perldoc.perl.org/perldoc.html#OPTIONS

**Comment by JohnMica** [comment]
this is similar to #15  and we are looking into fixing this compiling issue

**Comment by JohnMica** [comment]
this has been updated to reflect the fact they are bullets in a list
