### ISSUE TITLE
search does nothing

### ISSUE THREAD

**Issue by cup** [OpusVL/perldoc.perl.org#56]
1. Visit https://perldoc.perl.org

2. enter `say`

3. press enter

Nothing happens.

**Comment by JohnMica** [comment]
indeed - there are a few things missing from the search.

the search as been improved upon and will be released later on this week.

**Comment by cup** [comment]
:angry:

**Comment by cup** [comment]
is old site still available :angry:

**Comment by adinaa** [comment]
Searching doesn't work on the front page on initial load. It does on the front page if I select a version; and if I then go back to version 5.30.0 it works. 

Another example: Load the site. Type 'perlop' in the search box and hit return. Nothing happens. Click on the link for the FAQs page, and after that loads, type 'perlop' in the search box and hit return, and it works.

**Comment by cxw42** [comment]
Repro of @adinaa's experience.  From https://perldoc.perl.org/ , no results for `perlsyn`; from https://perldoc.perl.org/5.30.0/index-language.html , typing `perlsyn` in the search box and hitting Enter jumps straight to https://perldoc.perl.org/5.30.0/perlsyn.html .  Thanks!

**Comment by cxw42** [comment]
@cup Not as far as I know, but I have been using https://perldoc.pl (which I just recently learned about) in the meantime.

**Comment by denilsonsa** [comment]
Steps to reproduce it:

1. Open a new browser session (or incognito window).
2. Open the browser dev tools.
3. Open <https://perldoc.perl.org/>.
4. ⚠ BUG:
    > main.min.js:3 GET https://search.json/ net::ERR_TUNNEL_CONNECTION_FAILED
    > (index):1 Uncaught (in promise) TypeError: Failed to fetch
5. ⚠ Try to search for anything. It fails:
    > main.min.js:3 Uncaught TypeError: Cannot read property 'filter' of undefined
6. Choose a perl version.
7. Now there are no errors on the console, and the search works fine.

**Comment by JohnMica** [comment]
@denilson

Thanks for this. It does seem to be a missing file on initial load. I’ll let the server guys know about this issue. 

Regards,

John Mica

**Comment by JohnMica** [comment]
this is now fixed.

the search will work by default on the initial landing page as well.
