### ISSUE TITLE
getting keys and values from hashes

### ISSUE THREAD

**Issue by schultzdre** [OpusVL/perldoc.perl.org#57]
the example:

```
my @fruits = keys %fruit_colors;
my @colors = values %fruit_colors;
```

should actually be ```fruit_color``` not ```fruit_colors``` to agree with previous examples.

**Comment by karenetheridge** [comment]
The contents of the documentation are not managed in this repository.

However, I have applied your suggestion to the source, here: https://perl5.git.perl.org/perl.git/commitdiff/73560ddf61
