### ISSUE TITLE
Cannot view version 5.14 docs

### ISSUE THREAD

**Issue by brtastic** [OpusVL/perldoc.perl.org#59]
All other versions seem to work fine, but any subversion of 5.14 version returns error on main page (eg. https://perldoc.perl.org/5.14.0/):
```
403 Forbidden
You don't have permission to access /5.14.0/ on this server.
```

**Comment by JohnMica** [comment]
not sure what happened there - will check this out

**Comment by briandfoy** [comment]
I don't see this behavior. Is it still a problem?

**Comment by brtastic** [comment]
Seems like it's fixed now - can't reproduce anymore
