### ISSUE TITLE
code blocks overlap

### ISSUE THREAD

**Issue by rspier** [OpusVL/perldoc.perl.org#6]
See where [break] and [use feature] overlap, and [when] and [CORE ::] overlap.

![screenshot capture - 2018-12-21 - 20-18-06](https://user-images.githubusercontent.com/43223/50370546-8a2fda00-055d-11e9-9bb2-ff9b7ed32111.png)

**Comment by JohnMica** [comment]
I believe this was fixed in the release

- it you can retest or just give the URL it would be great

**Comment by rspier** [comment]
I can't replicate it anymore.
