### ISSUE TITLE
README.md spelling

### ISSUE THREAD

**Issue by philiprbrenan** [OpusVL/perldoc.perl.org#62]
During the development of this project at times it was **neccesary** for large binary files and 200k+ sets of smaller files be created, **beacause** of this the '.git' is an **enourmous** 400MiB and is incredible slow to work with, **infact** shells that automatically do fancy things with git (like zsh) will take seconds to even change directories.

"Will take" might be better as "took" as it is all safely in the past now.

**Comment by briandfoy** [comment]
For what it's worth, to fix this I forked the repo, edited the README inside GitHub without ever cloning it, and sent the PR. It's a pretty nice and quick way to get minor edits into the a repo. :)
