### ISSUE TITLE
Perl version is too prominent, gets confused with title of page

### ISSUE THREAD

**Issue by willsheppard** [OpusVL/perldoc.perl.org#65]
```
<h1>Perl 5 version 30.0 documentation</h1>
<h1>perlvar</h1>
```

The perl version "Perl 5 version 30.0 documentation" gets displayed right next to, and with the same visual weight as the name of the page "perlvar", it looks like one sentence that has been wrapped "Perl 5 version 30.0 documentation perlvar":
![image](https://user-images.githubusercontent.com/1519594/61447401-c63aea00-a948-11e9-8482-fce0c8217969.png)

It would look much clearer and be easier to read the page name "perlvar" if the design was more like this:
![image](https://user-images.githubusercontent.com/1519594/61447420-d0f57f00-a948-11e9-9357-ab91fd8fca76.png)
- the perl version is in the header, where it belongs
- the name of the page is the only h1

**Comment by JohnMica** [comment]
indeed - updated styles coming for all headings to better reflect their relation on the page

**Comment by willsheppard** [comment]
It's been over a month, this seems like a no-brainer. Do you need a pull request?

**Comment by willsheppard** [comment]
@JohnMica I'm looking forward to seeing the updated styles

**Comment by willsheppard** [comment]
Still waiting for the new styles...

**Comment by willsheppard** [comment]
If you're pressed for time, could you make the absolute bare minimum change temporarily?

Change this:
```
<h1 class="page-title">
```

To this:
```
<h7 class="page-title">
```

How did it ever make sense to have multiple `<h1>` tags in one page anyway?

**Comment by willsheppard** [comment]
I have raised a PR to address this: https://github.com/OpusVL/perldoc.perl.org-engine/pull/14

**Comment by willsheppard** [comment]
This has finally taken effect on the site, it looks great.
