### ISSUE TITLE
Issue with fileparser

### ISSUE THREAD

**Issue by ritishgumber** [OpusVL/perldoc.perl.org#76]
I am using the following code and it is returning unexpected result for suffix. Sample code below:

```
#perl 5.22.1 

use File::Basename;
@allowedTypes = (".png", ".jpg", ".jpeg", ".gif", ".bmp", ".tif", ".tiff", ".txt", ".html", ".xml", ".csv", ".doc", ".docx", ".xls", ".xlsx", ".pdf", ".sit", ".rar", ".zip");
my ($filename, $dirs, $suffix) = fileparse("/a/b/pod_jpeg.jpg", @allowedTypes);
print "Extension: ".$suffix."\n";
```

The expected result is : Extension: .jpg
Actual result: Extension: _jpeg.jpg

**Comment by Grinnz** [comment]
This is the bugtracker for the perldoc.perl.org website. See [perlbug](https://perldoc.pl/perlbug) for how to report bugs for Perl.
