### ISSUE TITLE
errors in JS console

### ISSUE THREAD

**Issue by rspier** [OpusVL/perldoc.perl.org#8]
Looks like something isn't right with jQuery?  

Chrome: Version 72.0.3626.17 (Official Build) beta (64-bit)

VM483 jquery.min.js:14 Uncaught TypeError: Cannot set property 'cssText' of undefined
    at VM483 jquery.min.js:14
    at VM483 jquery.min.js:14
    at VM483 jquery.min.js:14
(anonymous) @ VM483 jquery.min.js:14
(anonymous) @ VM483 jquery.min.js:14
(anonymous) @ VM483 jquery.min.js:14

VM484 common.js:37 Uncaught ReferenceError: $ is not defined
    at VM484 common.js:37
(anonymous) @ VM484 common.js:37

**Comment by rspier** [comment]
Actually, these may be related to the 
Google Voice https://chrome.google.com/webstore/detail/google-voice-by-google/kcnhkahnjcbndmmehfkdnkjomaanaooo
and 
Docs PDF/PowerPoint Viewer (by Google)  https://chrome.google.com/webstore/detail/docs-pdfpowerpoint-viewer/nnbmlagghjjcbdhgmkedmbmedengocbn

extensions.  But something about this site is making them unhappy.

**Comment by JohnMica** [comment]
cant replicate this issue.

i guess from the error that the extensions are loaded before jQuery has a chance to be present on the page therefor the ``` $ is not defined ```

**Comment by rspier** [comment]
I'm no longer seeing errors in the js console.

**Comment by JohnMica** [comment]
great news.

i'll close this off now
