### ISSUE TITLE
recommended use gramatical mistake

### ISSUE THREAD

**Issue by jasonblewis** [OpusVL/perldoc.perl.org#80]
in https://perldoc.perl.org/Pod/Usage.html in the Recommended Usage section

line 37 reads
`Print a brief help message and exits.`
probably should read
`Print a brief help message and exit.`

**Comment by Grinnz** [comment]
This is the bugtracker for the perldoc.perl.org website. Pod::Usage documentation bugs would be reported at https://rt.cpan.org/Public/Dist/Display.html?Name=Pod-Usage.

**Comment by karenetheridge** [comment]
That particular documentation page is sourced from https://metacpan.org/pod/Pod::Usage, which has its own bugtracker (see the Issues link in the left sidebar), not perl core.

**Comment by JohnMica** [comment]
thanks @Grinnz and @karenetheridge for the help
