### ISSUE TITLE
Symbolic reference used in an example in perlretut.html

### ISSUE THREAD

**Issue by 3ter** [OpusVL/perldoc.perl.org#83]
(If this is not the right spot to add suggestions regarding site contents, please point me to it 😄. I just clicked on that blue banner in the bottom-right corner.)

The [first example after the heading "Position information"](https://perldoc.perl.org/5.30.0/perlretut.html) throws an error while using strict.
```perl
$x = "Mmm...donut, thought Homer";
$x =~ /^(Mmm|Yech)\.\.\.(donut|peas)/; # matches
foreach $exp (1..$#-) {
    print "Match $exp: '${$exp}' at position ($-[$exp],$+[$exp])\n";
}
```
I'd suggest to use the list context just used before
```perl
$x = "Mmm...donut, thought Homer";
my @matches = ($x =~ /^(Mmm|Yech)\.\.\.(donut|peas)/); # matches
foreach $exp (1..$#-) {
    print "Match $exp: '$matches[$exp-1]' at position ($-[$exp],$+[$exp])\n";
}
```

**Comment by Grinnz** [comment]
The documentation is maintained by the Perl 5 Porters, you can use perlbug or perlbug@perl.org to submit a bug report.
